### PR TITLE
Fix messahe for queue cancelation past the deadline

### LINKED ISSUE #343: Deregister from event when still in queue
### What
You should be able to deregister from an event at any time if you are on the waiting list without paying the fine.

### Why
Currently, if you are in the waiting list you can not deregister after the deadline without paying a fine. This means that after the deadline when you are on the waiting list you can not really plan other things on this day because of the slim chance that you might get into the event. Because if you do get into the event, you would have to cancel the new plans you made and disappoint the new people or face the fine (which can be like 15 euros or more in some cases!). It also means that if you do plan other things that you can not give your spot to someone else on the waiting list. 

### Context
I think it makes sense that you would not be able to register again after deregistering after the deadline.

### PR DESCRIPTION
**Pull request by JAicewizard**
Closes #343 .

### Summary
This fixes the message when canceling after the deadline

### How to test
Steps to test the changes you made:
1. Go to an event that is past the deadline but you are in the queue
2. See message

### CODE REVIEW

File: lib/ui/screens/event_screen.dart [hunk 1]
```diff
@@ -552,41 +552,40 @@ class _EventScreenState extends State<EventScreen> {
...
-                        label: const Text('YES'),
-                      ),
-                    ],
-                  );
-                },
-              ) ??
-              false;
-        }
+        bool confirmed =
+            (event.cancelDeadlinePassed() && event.registration!.isInvited)
```
Comment (DeD1rk) [inline lib/ui/screens/event_screen.dart:556]: This doesn't make sense to me: "do you want to register" if already registered and invited?

Comment (JAicewizard) [reply lib/ui/screens/event_screen.dart:556]: thats a very good point, this whole section is kinda a mess so I misinterpreted the code while looking at it at a glance

**Review by DeD1rk — APPROVED** [review]
