### PR TITLE
Fix gallery backbutton

### LINKED ISSUE #321: Handle back presses when looking at a photo
### Describe the bug
Pressing back while looking at a photo goes back to the albums screen instead of album screen

### How to reproduce
1. Go to photos
2. go back
4. See that you are on the albums screen

### Expected behaviour
it should go back to the album screen

### Environment:
 - OS: android

### PR DESCRIPTION
**Pull request by DeD1rk**
Closes #321.

### Summary
This moves the gallery back into a dialog. It also turned out that keeping the initial gallery index in the cubit's state is not necessary. 

Meanwhile, I figured out an (I think) elegant way to change `DetailState` into a class tree. Although I don't really like the `x is Y` syntax being used a lot, I think this reduces the required boilerplate (especially the number of null checks/assertions to enforce non-nullability of results depending on the status) and complexity when extending DetailState (i.e. another non-generic subtype can simply be added).
I think a change like this will help in starting to refactor towards more flexible and conventional classes as they're used e.g. for authentication.

### How to test
Steps to test the changes you made:
1. Open a gallery.
2. Close it using the android back button.

### CODE REVIEW

File: lib/ui/screens/album_screen.dart [hunk 1]
```diff
@@ -49,39 +65,26 @@ class AlbumScreen extends StatelessWidget {
...
-      child: BlocBuilder<AlbumCubit, AlbumScreenState>(
+    return BlocProvider.value(
+      value: _cubit,
+      child: BlocBuilder<AlbumCubit, AlbumState>(
         builder: (context, state) {
           late final Widget body;
-          if (state.isLoading) {
-            body = const Center(child: CircularProgressIndicator());
-          } else if (state.hasException) {
+          if (state is ResultState) {
```
Comment (JAicewizard) [inline lib/ui/screens/album_screen.dart:73]: Maybe use a typeswitch for this, it doesnt look idea in dart but its nicer than if else

**Review by JAicewizard — COMMENTED** [review]
I still think moving it to an opaque screen is more appropriate as it is essentially a different screen, but the state changes are nice

File: lib/ui/screens/album_screen.dart (hunk 1 above)
Comment (DeD1rk) [reply lib/ui/screens/album_screen.dart:73]: That would be semantically different with subtyping (runtimetype does not match parent types). I think it'd be a good idea to find a consistent way to do this but I think this is fine for now. Perhaps later I can either use runtime type everywhere or add a helper method that swwitches between a number of closures:
```
state.switch(
  onLoading: (LoadingState state) {...},
  onError: (ErrorState state) {...},
  onResult: (ResultState state) {...},
  [else: (state) {...}],
)
```

Comment (JAicewizard) [reply lib/ui/screens/album_screen.dart:73]: I also like the idea of handling a lot of the common screen in a dedicated widget but we can discuss this next time not very important for this MR

**Review by JAicewizard — APPROVED** [review]
