### PR TITLE
Faster image scrolling and fix zoom out issue

### LINKED ISSUE #458: Can zoom to far out on photos
### Describe the bug
It is possible to zoom out too far on photos, auch that it becomes smaller thans the screen.

### How to reproduce
1. Go to a photo.
2. Zoom out.
3. See that it zooms out when it should stop.

### Expected behaviour
You should only be able to zoom out till the photo films the screen size to side.

### PR DESCRIPTION
**Pull request by rodepanda7**
Closes #458 

### Summary
Previously, you could zoom out on a photo in an album and it would stay zoomed out. 
Furthermore, photos are not cached correctly, so when you open a photo and scroll to the next one, the loading time is annoyingly long.

### How to test
Steps to test the changes you made:
1. Go to an album with a couple of photos so you can scroll a couple of times
2. Click on an image (I'd do the first one so you can scroll more)
3. Scroll a couple of times and the loading time will be a lot smaller. You can also zoom out and the photo will go back to the original size instead of a zoomed-out size.

### CODE REVIEW

File: lib/ui/widgets/gallery.dart [hunk 1]
```diff
@@ -169,9 +170,13 @@ class _GalleryState<C extends GalleryCubit> extends State<Gallery>
...
             child: RotatedBox(
-              quarterTurns: photos[i].rotation ~/ 90,
-              child: Image.network(photos[i].full),
-            ),
+                quarterTurns: photos[i].rotation ~/ 90,
+                child: CachedImage(
+                  imageUrl: photos[i].full,
+                  fit: BoxFit.contain,
+                  // placeholder:
+                  //     'assets/img/photo_placeholder_${(360 - photos[i].rotation) % 360}.png'),
```
Comment (JAicewizard) [inline lib/ui/widgets/gallery.dart:178]: This can go

File: lib/ui/widgets/gallery.dart [hunk 2]
```diff
@@ -181,7 +186,7 @@ class _GalleryState<C extends GalleryCubit> extends State<Gallery>
 
         return PhotoViewGalleryPageOptions.customChild(
           child: child,
-          minScale: PhotoViewComputedScale.contained * 0.8,
+          minScale: PhotoViewComputedScale.contained * 1,
```
Comment (JAicewizard) [inline lib/ui/widgets/gallery.dart:189]: Is there a reason this was changed? I cannot test this atm, I will test next week

**Review by JAicewizard — COMMENTED** [review]
Hey thanks for the PR! I will be there next week again, but thanks for starting with helping the app :)

File: lib/ui/widgets/gallery.dart (hunk 2 above)
Comment (ColonelPhantom) [reply lib/ui/widgets/gallery.dart:189]: With 0.8, you can zoom out the image from its default position. Not just 'pinch' it, but after that it will suddenly not take the full width up anymore, which we thought was pretty cursed. Putting it at 1 instead solves that so fully zoomed out is still the full screen width.
