### PR TITLE
Fix rotations

### LINKED ISSUE #366: Respect rotation of photos
### Describe the bug
Photos in an album can have a rotation passed along. We don't use that right now, and we probably should.
### How to reproduce
Look at e.g. photo 37 in the 'thalia on ice' album (https://thalia.nu/members/photos/thalia-on-ice/).

### Expected behaviour
All photos are upright.

### Additional context
I'm not sure why the website passes a rotation, instead of just serving pictures that are upright.

### PR DESCRIPTION
**Pull request by JAicewizard**
Closes #366 .

### Summary
This PR will assure that the rotation of photos matches the website

### How to test
Steps to test the changes you made:
1. Go to Photos
2. Click on any `test` album
3. check first image (I made it rotated on the website as well, check that it matches)

### CODE REVIEW

File: lib/ui/widgets/album_tile.dart [hunk 1]
```diff
@@ -13,9 +12,14 @@ class AlbumTile extends StatelessWidget {
     return Stack(
       fit: StackFit.expand,
       children: [
-        CachedImage(
```
Comment (DeD1rk) [inline lib/ui/widgets/album_tile.dart:16]: We need to keep caching though

**Review by DeD1rk — CHANGES_REQUESTED** [review]
I like the simplicity of just having 4 placeholders 😂

File: lib/ui/widgets/album_tile.dart (hunk 1 above)
Comment (JAicewizard) [reply lib/ui/widgets/album_tile.dart:16]: Whoops, this is why you dont copy paste lol, such a small PR...

**Review by JeeVee11 — APPROVED** [review]

**Review by DeD1rk — APPROVED** [review]
